# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: r4v3n-k
name: Eunjin Kwon
email: gej48443@gmail.com
footer_text: >
  <a href="https://github.com/r4v3n-k">Github</a>
  <a href="./">LinkedIn</a>
url: https://r4v3n-k.github.io/blog # the base hostname & protocol for your site

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: r4v3n-k

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus: true
disqus_shortname: r4v3n-k # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_number: true
rouge: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll-katex
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "1.0.0"
anchorjs_version: "3.2.2"
