name: Build and Deploy

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Setup plantuml plugin
        env:
          BASE_DIR: /opt/local/bin
        run: |
          JAR_PATH=$BASE_DIR/plantuml.jar
          # install and test plantuml
          mkdir -p $BASE_DIR
          wget https://github.com/plantuml/plantuml/releases/download/v1.2024.0/plantuml-gplv2-1.2024.0.jar
          mv plantuml-gplv2-1.2024.0.jar $JAR_PATH && chmod 777 $JAR_PATH
          java -jar $JAR_PATH -testdot
          # write a plugin script
          cat <<EOF > /usr/local/bin/plantuml
          #!/bin/bash
          java -jar /opt/local/bin/plantuml.jar "\$1" "\$2"
          EOF
          chmod +x /usr/local/bin/plantuml
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

